CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE user_role AS ENUM (
  'admin',
  'clerk',
  'viewer'
);

CREATE TYPE order_status AS ENUM (
  'pending',
  'confirmed',
  'dispatched',
  'delivered',
  'cancelled'
);


-- 2. USERS TABLE
-- Mirrors Supabase Auth users.
-- Supabase Auth handles password hashing + JWT.
-- We store profile/role data here.

CREATE TABLE users (
  id          UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  email       VARCHAR(255)  NOT NULL UNIQUE,
  full_name   VARCHAR(255)  NOT NULL,
  role        user_role     NOT NULL DEFAULT 'clerk',
  is_active   BOOLEAN       NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  users            IS 'Application user profiles — linked to Supabase Auth by id.';
COMMENT ON COLUMN users.role       IS 'admin: full access | clerk: own orders | viewer: read only';
COMMENT ON COLUMN users.is_active  IS 'Soft deactivation — never hard-delete users.';


-- 3. ORDERS TABLE

CREATE TABLE orders (
  id              UUID          PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number    VARCHAR(20)   NOT NULL UNIQUE,
  client_name     VARCHAR(255)  NOT NULL,
  mineral_type    VARCHAR(100)  NOT NULL,
  quantity_kg     NUMERIC(12,3) NOT NULL CHECK (quantity_kg > 0),
  unit_price_zar  NUMERIC(12,2) NOT NULL CHECK (unit_price_zar > 0),
  total_zar       NUMERIC(14,2) NOT NULL GENERATED ALWAYS AS (quantity_kg * unit_price_zar) STORED,
  status          order_status  NOT NULL DEFAULT 'pending',
  notes           TEXT,
  created_by      UUID          NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  orders               IS 'Mineral distribution orders.';
COMMENT ON COLUMN orders.order_number  IS 'Human-readable ID: ND-YYYY-XXXX. Generated by API.';
COMMENT ON COLUMN orders.total_zar     IS 'Computed: quantity_kg * unit_price_zar. Never set directly.';
COMMENT ON COLUMN orders.created_by    IS 'FK to users.id — who created this order.';


-- 4. AUDIT LOGS TABLE
-- Immutable. One row per field changed per event.
-- No UPDATE or DELETE permitted (enforced by trigger below).

CREATE TABLE audit_logs (
  id             UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id       UUID         NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  changed_by     UUID         NOT NULL REFERENCES users(id)  ON DELETE RESTRICT,
  field_changed  VARCHAR(100) NOT NULL,
  old_value      TEXT,
  new_value      TEXT,
  changed_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE audit_logs IS 'Immutable audit trail. One row per field changed per event.';


-- 5. INDEXES

CREATE INDEX idx_orders_status      ON orders(status);
CREATE INDEX idx_orders_created_at  ON orders(created_at DESC);
CREATE INDEX idx_orders_created_by  ON orders(created_by);
CREATE INDEX idx_orders_client_name ON orders(client_name);
CREATE INDEX idx_orders_mineral     ON orders(mineral_type);
CREATE INDEX idx_audit_order_id     ON audit_logs(order_id);
CREATE INDEX idx_audit_changed_by   ON audit_logs(changed_by);


-- 6. TRIGGERS

-- 6a. Auto-update orders.updated_at on every row change
CREATE OR REPLACE FUNCTION fn_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION fn_set_updated_at();


-- 6b. Prevent UPDATE or DELETE on audit_logs (tamper-proof)
CREATE OR REPLACE FUNCTION fn_protect_audit_logs()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Audit logs are immutable and cannot be modified or deleted.';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_audit_no_update
  BEFORE UPDATE ON audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION fn_protect_audit_logs();

CREATE TRIGGER trg_audit_no_delete
  BEFORE DELETE ON audit_logs
  FOR EACH ROW
  EXECUTE FUNCTION fn_protect_audit_logs();


-- 7. ROW LEVEL SECURITY
-- Backend uses service role (bypasses RLS).
-- RLS is a safety net for any accidental direct DB access.

ALTER TABLE users      ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders     ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "users_select_own"
  ON users FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "orders_select_authenticated"
  ON orders FOR SELECT
  TO authenticated
  USING (TRUE);

CREATE POLICY "orders_insert_authenticated"
  ON orders FOR INSERT
  TO authenticated
  WITH CHECK (created_by = auth.uid());

CREATE POLICY "audit_select_authenticated"
  ON audit_logs FOR SELECT
  TO authenticated
  USING (TRUE);


-- 8. SEED DATA
-- Step 1: Go to Supabase Dashboard > Authentication > Users > Add User
-- Step 2: Create the admin user there with their email + password
-- Step 3: Copy the UUID Supabase generates, paste it below, then run this insert

INSERT INTO users (id, email, full_name, role)
VALUES (
  'PASTE-SUPABASE-AUTH-UUID-HERE',
  'admin@ntsoakidistributions.co.za',
  'System Administrator',
  'admin'
);


-- 9. HELPER VIEW

CREATE OR REPLACE VIEW v_orders_with_creator AS
SELECT
  o.id,
  o.order_number,
  o.client_name,
  o.mineral_type,
  o.quantity_kg,
  o.unit_price_zar,
  o.total_zar,
  o.status,
  o.notes,
  o.created_at,
  o.updated_at,
  u.id        AS creator_id,
  u.full_name AS creator_name,
  u.email     AS creator_email
FROM orders o
JOIN users u ON o.created_by = u.id;

COMMENT ON VIEW v_orders_with_creator IS 'Orders joined with creator — used by API list and report queries.';


-- 10. VERIFY

SELECT
  t.table_name,
  COUNT(c.column_name) AS column_count
FROM information_schema.tables t
JOIN information_schema.columns c
  ON c.table_name = t.table_name
 AND c.table_schema = 'public'
WHERE t.table_schema = 'public'
  AND t.table_type = 'BASE TABLE'
GROUP BY t.table_name
ORDER BY t.table_name;

-- Expected:
-- audit_logs  | 7
-- orders      | 12
-- users       | 6
